package com.swayam.dms.db.model;

// Generated May 12, 2008 1:40:30 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Ward generated by hbm2java
 */
@Entity
@Table(name = "ward", schema = "public")
public class Ward implements java.io.Serializable {

    private int wardId;
    private String name;
    private Set<Complaint> complaints = new HashSet<Complaint>(0);

    public Ward() {
    }

    public Ward(int wardId, String name) {
        this.wardId = wardId;
        this.name = name;
    }

    public Ward(int wardId, String name, Set<Complaint> complaints) {
        this.wardId = wardId;
        this.name = name;
        this.complaints = complaints;
    }

    @Id
    @Column(name = "ward_id", unique = true, nullable = false)
    @GeneratedValue(generator = "sequence")
    @GenericGenerator(name = "sequence", strategy = "sequence", parameters = { @Parameter(name = "sequence", value = "ward_ward_id_seq") })
    public int getWardId() {
        return this.wardId;
    }

    public void setWardId(int wardId) {
        this.wardId = wardId;
    }

    @Column(name = "name", nullable = false, length = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "ward")
    public Set<Complaint> getComplaints() {
        return this.complaints;
    }

    public void setComplaints(Set<Complaint> complaints) {
        this.complaints = complaints;
    }

}
