package com.swayam.dms.db.model;

// Generated May 12, 2008 1:40:30 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "department", schema = "public")
public class Department implements java.io.Serializable {

    private int departmentId;
    private String name;
    private String shortName;
    private Set<Employee> employees = new HashSet<Employee>(0);
    private Set<Complaint> complaints = new HashSet<Complaint>(0);

    public Department() {
    }

    public Department(int departmentId) {
        this.departmentId = departmentId;
    }

    public Department(int departmentId, String name, String shortName,
            Set<Employee> employees, Set<Complaint> complaints) {
        this.departmentId = departmentId;
        this.name = name;
        this.shortName = shortName;
        this.employees = employees;
        this.complaints = complaints;
    }

    @Id
    @Column(name = "department_id", unique = true, nullable = false)
    @GeneratedValue(generator = "sequence")
    @GenericGenerator(name = "sequence", strategy = "sequence", parameters = { @Parameter(name = "sequence", value = "department_department_id_seq") })
    public int getDepartmentId() {
        return this.departmentId;
    }

    public void setDepartmentId(int departmentId) {
        this.departmentId = departmentId;
    }

    @Column(name = "name", length = 20)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "short_name", length = 5)
    public String getShortName() {
        return this.shortName;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "department")
    public Set<Employee> getEmployees() {
        return this.employees;
    }

    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "department")
    public Set<Complaint> getComplaints() {
        return this.complaints;
    }

    public void setComplaints(Set<Complaint> complaints) {
        this.complaints = complaints;
    }

}
