/*
 * PreferenceSetterDialog.java
 *
 * Created on September 27, 2008, 2:38 AM
 *  
 * Copyright (c) 2002 - 2008 : Swayam Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.swayam.bhasha.prefs;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

import com.swayam.bhasha.utils.page.IndicPane;
import com.swayam.generic.utils.FontLoader;
import com.swayam.generic.utils.JComboUtils;

/**
 * 
 * @author paawak
 */
public class PreferenceSetterDialog extends javax.swing.JDialog {

    private static final long serialVersionUID = -5294475119573092069L;
    public static final String BANGLA = "Bangla";
    public static final String HINDI = "Hindi";
    private final String SELECT_ONE_STR = "-----Select One-----";

    private String defaultLanguageName = null;
    private final List<String> selectedLanguageNamesVec = new ArrayList<String>();

    /** Creates new form PreferenceSetterDialog */
    public PreferenceSetterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        loadFont(BANGLA);
        loadFont(HINDI);

        JComboUtils.fillComboWithNewArray(cbFontSize, IndicPane.FONT_SIZE_ARRAY);

        selectedLanguageNamesVec.add(SELECT_ONE_STR);

    }

    private void loadFont(String language) {

        boolean isBangla = language.equals(BANGLA);

        Set<String> fonts = isBangla ? FontLoader.getBanglaFonts() : FontLoader.getHindiFonts();

        if (fonts.isEmpty()) {
            int option = JOptionPane.showConfirmDialog(this, language + " fonts not found. Are you sure you want to continue?", "No " + language + " Fonts",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (option == JOptionPane.YES_OPTION) {
                (isBangla ? pnlBangla : pnlHindi).setVisible(false);
            } else {
                System.exit(1);
            }

        } else {
            JComboUtils.fillComboWithNewArray(isBangla ? cbBanglaFonts : cbHindiFonts, fonts);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlBangla = new javax.swing.JPanel();
        chBangla = new javax.swing.JCheckBox();
        cbBanglaFonts = new javax.swing.JComboBox();
        pnlHindi = new javax.swing.JPanel();
        chHindi = new javax.swing.JCheckBox();
        cbHindiFonts = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlDefaultLanguage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbLanguages = new javax.swing.JComboBox();
        pnlButtons = new javax.swing.JPanel();
        btSaveSettings = new javax.swing.JButton();
        pnlDefaultLanguage1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbFontSize = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("First time configuration");

        jLabel1.setText("Select the languages you want supported, with your preferred font");

        chBangla.setText("Bangla");
        chBangla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chBanglaItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlBanglaLayout = new org.jdesktop.layout.GroupLayout(pnlBangla);
        pnlBangla.setLayout(pnlBanglaLayout);
        pnlBanglaLayout.setHorizontalGroup(pnlBanglaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                pnlBanglaLayout.createSequentialGroup().add(18, 18, 18).add(chBangla).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 80, Short.MAX_VALUE).add(
                        cbBanglaFonts, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 253, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(52, 52, 52)));
        pnlBanglaLayout.setVerticalGroup(pnlBanglaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                pnlBanglaLayout.createSequentialGroup().addContainerGap().add(
                        pnlBanglaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(chBangla).add(cbBanglaFonts,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE)));

        chHindi.setText("Hindi");
        chHindi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chHindiItemStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pnlHindiLayout = new org.jdesktop.layout.GroupLayout(pnlHindi);
        pnlHindi.setLayout(pnlHindiLayout);
        pnlHindiLayout.setHorizontalGroup(pnlHindiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                pnlHindiLayout.createSequentialGroup().add(18, 18, 18).add(chHindi).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 81, Short.MAX_VALUE).add(cbHindiFonts,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 263, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(50, 50, 50)));
        pnlHindiLayout.setVerticalGroup(pnlHindiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                pnlHindiLayout.createSequentialGroup().addContainerGap().add(
                        pnlHindiLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(chHindi).add(cbHindiFonts, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)).addContainerGap(20, Short.MAX_VALUE)));

        jLabel2.setText("Languages");

        jLabel3.setText("Available Fonts");

        pnlDefaultLanguage.setLayout(null);

        jLabel4.setText("Preferred Language:");
        pnlDefaultLanguage.add(jLabel4);
        jLabel4.setBounds(0, 10, 140, 20);

        cbLanguages.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbLanguagesItemStateChanged(evt);
            }
        });
        pnlDefaultLanguage.add(cbLanguages);
        cbLanguages.setBounds(160, 10, 260, 24);

        pnlButtons.setLayout(null);

        btSaveSettings.setText("Save Settings");
        btSaveSettings.setEnabled(false);
        btSaveSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btSaveSettingsMouseReleased(evt);
            }
        });
        pnlButtons.add(btSaveSettings);
        btSaveSettings.setBounds(120, 20, 170, 25);

        pnlDefaultLanguage1.setLayout(null);

        jLabel5.setText("Preferred Font Size:");
        pnlDefaultLanguage1.add(jLabel5);
        jLabel5.setBounds(0, 10, 140, 20);

        cbFontSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFontSizeItemStateChanged(evt);
            }
        });
        pnlDefaultLanguage1.add(cbFontSize);
        cbFontSize.setBounds(160, 10, 260, 24);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1,
                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE).add(
                org.jdesktop.layout.GroupLayout.TRAILING,
                layout.createSequentialGroup().addContainerGap().add(pnlBangla, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)).add(layout.createSequentialGroup().add(29, 29, 29).add(jLabel2).add(133, 133, 133).add(jLabel3).addContainerGap(157, Short.MAX_VALUE))
                .add(
                        layout.createSequentialGroup().addContainerGap().add(pnlHindi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)).add(
                        layout.createSequentialGroup().addContainerGap().add(pnlDefaultLanguage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 435,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(35, Short.MAX_VALUE)).add(
                        layout.createSequentialGroup().add(39, 39, 39).add(pnlButtons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 400,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(43, Short.MAX_VALUE)).add(
                        layout.createSequentialGroup().addContainerGap().add(pnlDefaultLanguage1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 435,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap(35, Short.MAX_VALUE)));
        layout.setVerticalGroup(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().add(jLabel1).add(14, 14, 14).add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE).add(jLabel2).add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED).add(pnlBangla, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                                org.jdesktop.layout.LayoutStyle.UNRELATED).add(pnlHindi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(
                                org.jdesktop.layout.LayoutStyle.RELATED).add(pnlDefaultLanguage, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 15, Short.MAX_VALUE).add(
                                pnlDefaultLanguage1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).add(18, 18, 18).add(
                                pnlButtons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap()));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width - 488) / 2, (screenSize.height - 427) / 2, 488, 427);
    }// </editor-fold>//GEN-END:initComponents

    private void chBanglaItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-
        // FIRST
        // :
        // event_chBanglaItemStateChanged

        languageCheckBoxItemStateChanged(chBangla, BANGLA);

    }// GEN-LAST:event_chBanglaItemStateChanged

    private void chHindiItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-
        // FIRST
        // :
        // event_chHindiItemStateChanged

        languageCheckBoxItemStateChanged(chHindi, HINDI);

    }// GEN-LAST:event_chHindiItemStateChanged

    private void cbLanguagesItemStateChanged(java.awt.event.ItemEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_cbLanguagesItemStateChanged
        if (cbLanguages.getSelectedIndex() > 0) {

            defaultLanguageName = cbLanguages.getSelectedItem().toString();

            btSaveSettings.setEnabled(true);
        }
    }// GEN-LAST:event_cbLanguagesItemStateChanged

    private void btSaveSettingsMouseReleased(java.awt.event.MouseEvent evt) {// GEN
        // -
        // FIRST
        // :
        // event_btSaveSettingsMouseReleased
        saveDataToSystem();
        setVisible(false);
        dispose();
    }// GEN-LAST:event_btSaveSettingsMouseReleased

    private void cbFontSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-
        // FIRST
        // :
        // event_cbFontSizeItemStateChanged
        // TODO add your handling code here:
    }// GEN-LAST:event_cbFontSizeItemStateChanged

    private void languageCheckBoxItemStateChanged(JCheckBox chbLanguage, String languageName) {

        if (chbLanguage.isSelected()) {
            if (!selectedLanguageNamesVec.contains(languageName)) {
                // check whether fonts are available for the selected language
                if ((languageName.equals(BANGLA) && FontLoader.getBanglaFonts().size() == 0) || (languageName.equals(HINDI) && FontLoader.getHindiFonts().size() == 0)) {
                    String[] options = { "Don't need " + languageName, "Exit From Application" };
                    int selectedOption = JOptionPane.showOptionDialog(this, "No suitable fonts installed for " + languageName, languageName + " font not found:",
                            JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE, null, options, options[0]);

                    if (selectedOption == 0) {
                        chbLanguage.setSelected(false);
                    } else {
                        System.exit(0);
                    }

                } else {
                    selectedLanguageNamesVec.add(languageName);
                    JComboUtils.fillComboWithNewArray(cbLanguages, selectedLanguageNamesVec);
                }
            }
        } else {
            selectedLanguageNamesVec.remove(languageName);
            JComboUtils.fillComboWithNewArray(cbLanguages, selectedLanguageNamesVec);
        }

        if (cbLanguages.getItemCount() < 2) {
            pnlDefaultLanguage.setVisible(false);
        } else {
            pnlDefaultLanguage.setVisible(true);
        }
    }

    private void saveDataToSystem() {
        Map<Locale, String> languageFontMap = new HashMap<Locale, String>();
        languageFontMap.put(IndicPane.BANGLA_LOCALE, (String) cbBanglaFonts.getSelectedItem());
        languageFontMap.put(IndicPane.HINDI_LOCALE, (String) cbHindiFonts.getSelectedItem());
        UserPreferencesImpl prefs = new UserPreferencesImpl();
        prefs.setDefaultLanguage(defaultLanguageName.equals(BANGLA) ? IndicPane.BANGLA_LOCALE : IndicPane.HINDI_LOCALE);
        prefs.setLanguageToFontMap(languageFontMap);
        prefs.setPreferredFontSize(Integer.valueOf((String) cbFontSize.getSelectedItem()));
        prefs.save();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSaveSettings;
    private javax.swing.JComboBox cbBanglaFonts;
    private javax.swing.JComboBox cbFontSize;
    private javax.swing.JComboBox cbHindiFonts;
    private javax.swing.JComboBox cbLanguages;
    private javax.swing.JCheckBox chBangla;
    private javax.swing.JCheckBox chHindi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlBangla;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlDefaultLanguage;
    private javax.swing.JPanel pnlDefaultLanguage1;
    private javax.swing.JPanel pnlHindi;
    // End of variables declaration//GEN-END:variables

}
