package com.swayam.dms.db.model;

// Generated May 12, 2008 1:40:30 AM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * ComplaintType generated by hbm2java
 */
@Entity
@Table(name = "complaint_type", schema = "public")
public class ComplaintType implements java.io.Serializable {

    private int complaintTypeId;
    private String shortDescription;
    private String details;
    private Set<Complaint> complaints = new HashSet<Complaint>(0);

    public ComplaintType() {
    }

    public ComplaintType(int complaintTypeId, String shortDescription,
            String details) {
        this.complaintTypeId = complaintTypeId;
        this.shortDescription = shortDescription;
        this.details = details;
    }

    public ComplaintType(int complaintTypeId, String shortDescription,
            String details, Set<Complaint> complaints) {
        this.complaintTypeId = complaintTypeId;
        this.shortDescription = shortDescription;
        this.details = details;
        this.complaints = complaints;
    }

    @Id
    @Column(name = "complaint_type_id", unique = true, nullable = false)
    @GeneratedValue(generator = "sequence")
    @GenericGenerator(name = "sequence", strategy = "sequence", parameters = { @Parameter(name = "sequence", value = "complaint_type_complaint_type_id_seq") })
    public int getComplaintTypeId() {
        return this.complaintTypeId;
    }

    public void setComplaintTypeId(int complaintTypeId) {
        this.complaintTypeId = complaintTypeId;
    }

    @Column(name = "short_description", nullable = false)
    public String getShortDescription() {
        return this.shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    @Column(name = "details", nullable = false)
    public String getDetails() {
        return this.details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "complaintType")
    public Set<Complaint> getComplaints() {
        return this.complaints;
    }

    public void setComplaints(Set<Complaint> complaints) {
        this.complaints = complaints;
    }

}
