package com.swayam.dms.web.model;

// Generated May 12, 2008 1:40:30 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComplaintHistoryId generated by hbm2java
 */
@Embeddable
public class ComplaintHistoryId implements java.io.Serializable {

    private long complaintId;
    private long changedBy;
    private String oldState;
    private String newState;
    private Date changedAt;

    public ComplaintHistoryId() {
    }

    public ComplaintHistoryId(long complaintId, long changedBy,
            String oldState, String newState) {
        this.complaintId = complaintId;
        this.changedBy = changedBy;
        this.oldState = oldState;
        this.newState = newState;
    }

    public ComplaintHistoryId(long complaintId, long changedBy,
            String oldState, String newState, Date changedAt) {
        this.complaintId = complaintId;
        this.changedBy = changedBy;
        this.oldState = oldState;
        this.newState = newState;
        this.changedAt = changedAt;
    }

    @Column(name = "complaint_id", nullable = false)
    public long getComplaintId() {
        return this.complaintId;
    }

    public void setComplaintId(long complaintId) {
        this.complaintId = complaintId;
    }

    @Column(name = "changed_by", nullable = false)
    public long getChangedBy() {
        return this.changedBy;
    }

    public void setChangedBy(long changedBy) {
        this.changedBy = changedBy;
    }

    @Column(name = "old_state", nullable = false)
    public String getOldState() {
        return this.oldState;
    }

    public void setOldState(String oldState) {
        this.oldState = oldState;
    }

    @Column(name = "new_state", nullable = false)
    public String getNewState() {
        return this.newState;
    }

    public void setNewState(String newState) {
        this.newState = newState;
    }

    @Column(name = "changed_at", length = 8)
    public Date getChangedAt() {
        return this.changedAt;
    }

    public void setChangedAt(Date changedAt) {
        this.changedAt = changedAt;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof ComplaintHistoryId))
            return false;
        ComplaintHistoryId castOther = (ComplaintHistoryId) other;

        return (this.getComplaintId() == castOther.getComplaintId())
                && (this.getChangedBy() == castOther.getChangedBy())
                && ((this.getOldState() == castOther.getOldState()) || (this
                        .getOldState() != null
                        && castOther.getOldState() != null && this
                        .getOldState().equals(castOther.getOldState())))
                && ((this.getNewState() == castOther.getNewState()) || (this
                        .getNewState() != null
                        && castOther.getNewState() != null && this
                        .getNewState().equals(castOther.getNewState())))
                && ((this.getChangedAt() == castOther.getChangedAt()) || (this
                        .getChangedAt() != null
                        && castOther.getChangedAt() != null && this
                        .getChangedAt().equals(castOther.getChangedAt())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getComplaintId();
        result = 37 * result + (int) this.getChangedBy();
        result = 37 * result
                + (getOldState() == null ? 0 : this.getOldState().hashCode());
        result = 37 * result
                + (getNewState() == null ? 0 : this.getNewState().hashCode());
        result = 37 * result
                + (getChangedAt() == null ? 0 : this.getChangedAt().hashCode());
        return result;
    }

}
