CREATE SEQUENCE hibernate_sequence 
START WITH 1
INCREMENT BY 1;


CREATE TABLE TIMESTAMP_DEMO ( 
	ID				NUMBER(6) PRIMARY KEY NOT NULL,
	NAME			VARCHAR2(20) NOT NULL,
	TIME_WITH_ZONE	TIMESTAMP(9) WITH TIME ZONE NOT NULL,
	TIME_WITH_ZONE_LOCAL	TIMESTAMP(9) WITH LOCAL TIME ZONE
    ) ;
    

    
