
package view;

import javax.swing.*;
import javax.swing.JOptionPane;
import java.awt.event.*;
import java.awt.*;
import java.io.*;



/**
 *
 * @author  Palash
 */
public class InventoryPanel extends javax.swing.JPanel {
    
    /** Creates new form MotorPanel */
    public InventoryPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jScrollPanelHolder = new javax.swing.JScrollPane();
        jPnlStatus = new javax.swing.JPanel();
        txtStatus = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        pnlTitle.setLayout(new java.awt.BorderLayout());

        pnlTitle.setBackground(new java.awt.Color(204, 204, 255));
        lblTitle.setBackground(new java.awt.Color(204, 204, 255));
        lblTitle.setFont(new java.awt.Font("Bookman Old Style", 1, 18));
        lblTitle.setForeground(new java.awt.Color(204, 51, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Inventory Management System");
        pnlTitle.add(lblTitle, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(pnlTitle, gridBagConstraints);

        jScrollPanelHolder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPanelHolder.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 798;
        gridBagConstraints.ipady = 898;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPanelHolder, gridBagConstraints);

        jPnlStatus.setLayout(null);

        jPnlStatus.setBackground(new java.awt.Color(255, 255, 204));
        jPnlStatus.setMinimumSize(new java.awt.Dimension(20, 28));
        jPnlStatus.setPreferredSize(new java.awt.Dimension(50, 28));
        txtStatus.setBackground(new java.awt.Color(255, 255, 204));
        txtStatus.setEditable(false);
        txtStatus.setText(" ");
        jPnlStatus.add(txtStatus);
        txtStatus.setBounds(73, 2, 830, 24);

        lblStatus.setBackground(new java.awt.Color(204, 204, 255));
        lblStatus.setFont(new java.awt.Font("Dialog", 0, 12));
        lblStatus.setForeground(new java.awt.Color(204, 51, 0));
        lblStatus.setText("Status:");
        lblStatus.setBorder(new javax.swing.border.EtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255)));
        jPnlStatus.add(lblStatus);
        lblStatus.setBounds(0, 3, 67, 20);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 750;
        gridBagConstraints.ipady = 2;
        add(jPnlStatus, gridBagConstraints);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtStatus;
    private javax.swing.JPanel jPnlStatus;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JScrollPane jScrollPanelHolder;
    // End of variables declaration//GEN-END:variables
    
    
    public void setBodyPanel(JPanel Panel)
    {
	jScrollPanelHolder.getViewport().setView(Panel);
    }    
    
   /* public void setBodyPanel(javax.swing.JFrame Frame)
    {
	jScrollPanelHolder.getViewport().setView(Frame.show());
        
        //Frame.show();
        
    }  //*/      
    
}
